#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-helpers

# Build the image
auto/build-docker-images

# Login dockerhub
auto/auth-with-dockerhub

# Release
function push_image() {
  display_status "Release to registry"
  docker tag ${PROJECT_NAME}_${1} ${REPO_NAMESPACE}/${2}
  docker tag ${PROJECT_NAME}_${1} ${REPO_NAMESPACE}/${2}:${GIT_HASH}
  docker push ${REPO_NAMESPACE}/${2}
  docker push ${REPO_NAMESPACE}/${2}:${GIT_HASH}
  display_status "Pushed docker image ${REPO_NAMESPACE}/${2} with tags ${GIT_HASH}, latest"
}

push_image app ${APP_NAME}
push_image migration ${MIGRATION_NAME}

docker logout
